// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaTYjlTvUC2yILl4TUw3uj4lRfstue6VU',
    appId: '1:328194674523:web:4cece55892d2b57ea3147e',
    messagingSenderId: '328194674523',
    projectId: 'flutter-faq-27a4d',
    authDomain: 'flutter-faq-27a4d.firebaseapp.com',
    databaseURL: 'https://flutter-faq-27a4d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-faq-27a4d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTH7fK9-mB-zZXN2JOTDaNAFnVRt0JTd4',
    appId: '1:328194674523:android:e165ad680484e347a3147e',
    messagingSenderId: '328194674523',
    projectId: 'flutter-faq-27a4d',
    databaseURL: 'https://flutter-faq-27a4d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-faq-27a4d.appspot.com',
  );
}
